version: '3.8'

services:
  pagamento-api:
    build: .
    container_name: ms-pagamento-api-dev
    depends_on:
      db-pagamento:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-pagamento:3306/pagamento_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: pagamento_user
      SPRING_DATASOURCE_PASSWORD: secure_password_pagamento
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - pedido-net

networks:
  pedido-net:
    external: true